version: '3.4'

services:
  mongodb:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
  keystone:
    build: '.'
    ports:
      - 3000:3000
    links:
      - mongodb
    volumes:
      - ./models:/usr/src/app/models
    environment:
      ADMIN_USER: user@keystone.js
      ADMIN_PASSWORD: admin
      MONGODB: 'mongodb://mongodb:27017'
      COOKIE_SECRET: 'supersecret'
